### PR TITLE
sheetal jain portfolio - Upate

### PR DESCRIPTION
**Pull request by minhaj-313**
Update the Scroll bar.
Update Favicon
Clean Code
etc...

### CODE REVIEW

**Comment by minhaj-313** [comment]
please accept my PR as Hacktober-Accepted, Thank You in Advance.

**Comment by sheetalj2205** [comment]
> please accept my PR as Hacktober-Accepted, Thank You in Advance.

Please share the screenshots of changes that you did

**Comment by minhaj-313** [comment]
> > please accept my PR as Hacktober-Accepted, Thank You in Advance.
> 
> Please share the screenshots of changes that you did

Ok Wait I will send you

**Comment by minhaj-313** [comment]
https://minhaj-313.github.io/portfolio/  
see by this link You will see directly.
I do these Things..
Update the Scroll bar.
Update Favicon
Clean Code 
etc...
Thank You Again. 
Nice to Meet You.....

**Comment by minhaj-313** [comment]
image

**Comment by minhaj-313** [comment]
Thank You So Much dear, Nice Expirience with This Project, Thank you very Much again for giving me this great opportunity of working on Your Project.

**Pull request merged**
